package net.Chipperfluff.chipi.sound;

import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

import net.Chipperfluff.chipi.ChipiMod;

public class ModSounds {

    public static final SoundEvent MEP_MILK = register("entity.mep.milk");
    public static final SoundEvent PLAYER_MILK_SONG = register("player_milk_song");

    private static SoundEvent register(String id) {
        Identifier identifier = new Identifier(ChipiMod.MOD_ID, id);
        return Registry.register(
            Registries.SOUND_EVENT,
            identifier,
            SoundEvent.of(identifier)
        );
    }

    public static void register() {}
}
