package net.Chipperfluff.chipi.entity;

import net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder;
import net.minecraft.entity.EntityDimensions;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.SpawnGroup;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public final class ModEntities {

    public static final EntityType<MepEntity> MEP =
        Registry.register(
            Registries.ENTITY_TYPE,
            new Identifier("chipi", "mep"),
            FabricEntityTypeBuilder
                .create(SpawnGroup.CREATURE, MepEntity::new)
                .dimensions(EntityDimensions.fixed(0.6f, 1.95f))
                .build()
        );

    public static final EntityType<PlayerJrEntity> PLAYER_JR =
        Registry.register(
            Registries.ENTITY_TYPE,
            new Identifier("chipi", "player_jr"),
            FabricEntityTypeBuilder
                .create(SpawnGroup.CREATURE, PlayerJrEntity::new)
                .dimensions(EntityDimensions.fixed(0.45f, 0.9f)) // small
                .build()
    );

    private ModEntities() {}
}
