package net.Chipperfluff.chipi.effect;

import net.minecraft.entity.effect.StatusEffect;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

import net.Chipperfluff.chipi.ChipiMod;

public class ModEffects {

    public static final StatusEffect CHIPI_BLESSING = new ChipiBlessingEffect();
    public static final StatusEffect PREGNANT = new PregnantEffect();

    public static void register() {
        Registry.register(
            Registries.STATUS_EFFECT,
            new Identifier(ChipiMod.MOD_ID, "chipi_blessing"),
            CHIPI_BLESSING
        );

        Registry.register(
            Registries.STATUS_EFFECT,
            new Identifier(ChipiMod.MOD_ID, "pregnant"),
            PREGNANT
        );
    }
}
